const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Product = sequelize.define('Product', {
    id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true
    },
    title: { type: DataTypes.STRING, allowNull: false },
    brand: { type: DataTypes.STRING },
    category: { type: DataTypes.STRING },
    subCategory: { type: DataTypes.STRING },
    fabricType: { type: DataTypes.STRING },
    color: { type: DataTypes.STRING },
    barcode: { type: DataTypes.STRING },
    sku: { type: DataTypes.STRING, unique: true, allowNull: true },
    imageUrl: { type: DataTypes.TEXT },
    purchasePrice: { type: DataTypes.FLOAT, defaultValue: 0 },
    wholesalePrice: { type: DataTypes.FLOAT, defaultValue: 0 },
    retailPrice: { type: DataTypes.FLOAT, defaultValue: 0 },
    minSellingRate: { type: DataTypes.FLOAT, defaultValue: 0 },
    stockUnit: { type: DataTypes.STRING, defaultValue: 'Meter' },
    sellUnit: { type: DataTypes.STRING, defaultValue: 'Gaz' },
    metersPerSellUnit: { type: DataTypes.FLOAT, defaultValue: 0.9144 },
    stockMeters: { type: DataTypes.FLOAT, defaultValue: 0 },
    minWholesaleQty: { type: DataTypes.FLOAT, defaultValue: 1 },
    bedsheetSize: { type: DataTypes.STRING, allowNull: true },
    bedsheetSetType: { type: DataTypes.STRING, allowNull: true },
    bedsheetDimensions: { type: DataTypes.STRING, allowNull: true },
    pillowCoverSize: { type: DataTypes.STRING, allowNull: true },
    pillowCoverCount: { type: DataTypes.INTEGER, allowNull: true },
    bedsheetWeight: { type: DataTypes.FLOAT, allowNull: true },
    bedsheetWeightUnit: { type: DataTypes.STRING, allowNull: true },
    blanketPly: { type: DataTypes.STRING, allowNull: true },
    blanketSize: { type: DataTypes.STRING, allowNull: true },
    blanketWeight: { type: DataTypes.FLOAT, allowNull: true },
    blanketMaterial: { type: DataTypes.STRING, allowNull: true },
    storePublished: { type: DataTypes.BOOLEAN, defaultValue: true },
    storeFeatured: { type: DataTypes.BOOLEAN, defaultValue: false },
    storeNewArrival: { type: DataTypes.BOOLEAN, defaultValue: false },
    storeSale: { type: DataTypes.BOOLEAN, defaultValue: false },
    storeOnlinePrice: { type: DataTypes.FLOAT, allowNull: true },
    storeDiscountPrice: { type: DataTypes.FLOAT, allowNull: true },
    storeSortOrder: { type: DataTypes.INTEGER, defaultValue: 0 },
    storeDescription: { type: DataTypes.TEXT, allowNull: true },
    storeTags: { type: DataTypes.STRING, allowNull: true },
    storeHomeSection: { type: DataTypes.STRING, allowNull: true, defaultValue: 'featured' },
    storeTitle: { type: DataTypes.STRING, allowNull: true },
    storeShortDescription: { type: DataTypes.STRING(240), allowNull: true },
    storeImages: { type: DataTypes.TEXT, allowNull: true },
    storeStickerImage: { type: DataTypes.TEXT, allowNull: true },
    storeStickerJson: { type: DataTypes.TEXT, allowNull: true },
    storeHighlights: { type: DataTypes.TEXT, allowNull: true },
    storeDeliveryTime: { type: DataTypes.STRING, allowNull: true },
    storeDeliveryCharge: { type: DataTypes.STRING, allowNull: true },
    storeDeliveryDetail: { type: DataTypes.TEXT, allowNull: true },
    storeReturnPolicy: { type: DataTypes.TEXT, allowNull: true },
    storeDescHeadline: { type: DataTypes.STRING, allowNull: true },
    storeDescBody: { type: DataTypes.TEXT, allowNull: true },
    storeFeatures: { type: DataTypes.TEXT, allowNull: true },
    storeIncludes: { type: DataTypes.TEXT, allowNull: true },
    storeCare: { type: DataTypes.TEXT, allowNull: true },
    compatibility: { type: DataTypes.STRING, allowNull: true },
    warrantyType: { type: DataTypes.STRING, allowNull: true },
    supplierId: { type: DataTypes.INTEGER },
    ShopId: { type: DataTypes.INTEGER, defaultValue: 1 },
    shopId: { type: DataTypes.UUID, allowNull: true, field: 'shop_uuid' }
});

module.exports = Product;
